services:
  island-green-backend-api-dev:
    build:
      context: .
      dockerfile: DockerFile.dev
    ports:
      - "1111:1111"
    environment:
      - NODE_ENV=development
      - PORT=1111
    volumes:
      - ./src:/usr/src/app/src

  mysql_db:
    image: mysql
    ports: 
    - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: island_green_db_v1
      - MYSQL_USER: island_green_user
      - MYSQL_PASSWORD: island_green_password
      - MYSQL_TCP_PORT: 3307

